# Color anchors are defined in ~/.config/wal/templates/yambar.yml
trans: &trans 00000000

# Fonts
ios: &ios Iosevka:pixelsize=20:fontfeatures=ss20:style=bold
icons: &icons Font Awesome 6 free:style=solid:pixelsize=20

# Modules
i3: &i3
  i3:
    anchors:
      - string: &default {margin: 5, on-click: "swaymsg --quiet workspace {name}", text:  "{name}"}
      - focused: &focused
          foreground: *background
          deco:
            background: 
              color: *color4
      - unfocused: &unfocused
          foreground: *color4
          deco:
            background: 
              color: *background
    sort: ascending
    content:
      "":
        map:
          conditions:
            state == focused: {string: {<<: [*default, *focused], margin: 8}}
            state != focused: {string: {<<: [*default, *unfocused], margin: 8}}

mpd: &mpd
  mpd:
    foreground: *color6
    host: /run/mpd/socket
    content:
      map:
        conditions:
          state != offline:
            string:
              text: "{artist} - {title} ({album})"
              deco:
                background:
                  color: *background

pipewire: &pipewire
  pipewire:
    foreground: *color2
    content:
      map:
        conditions:
          type == "sink" && muted:
            string:
              margin: 4
              text: "[volume: mute]"
              on-click: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
              deco:
                background:
                  color: *background
          type == "sink" && ~muted:
            string:
              margin: 4
              text: "[volume: {cubic_volume}%]"
              on-click:
                left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
                wheel-up: "pactl set-sink-volume @DEFAULT_SINK@ +1%"
                wheel-down: "pactl set-sink-volume @DEFAULT_SINK@ -1%"
              deco:
                background:
                  color: *background

network: &network
  network:
    foreground: *color3
    content:
      map:
        conditions:
          state == up && carrier:
            string:
              margin: 4
              text: "[{ssid}: {quality}%]"
              deco:
                background:
                  color: *background

battery: &battery
  battery:
    foreground: *color1
    name: BAT1
    poll-interval: 30000
    content:
      map:
        conditions:
          capacity != 0:
            string:
              margin: 4
              text: "[battery: {capacity}%]"
              deco:
                background:
                  color: *background

clock: &clock
  clock:
    foreground: *foreground
    time-format: "%H:%M"
    date-format: "%a, %b %d"
    content:
      string: 
        margin: 4
        text: "{time} | {date}"
        deco:
          background:
            color: *background

bar:
  height: 28
  location: top
  #right-margin: 4
  #border:
    #top-width: 5

  font: IosevkaNerdFont:pixelsize=16:fontfeatures=ss20
=======
  sort: ascending
  anchors:
    - string: &default {text:  "{name}", margin: 5, on-click: "swaymsg --quiet workspace {name}"}
    - focused: &focused {foreground: *bg, <<: *c2b}
  content:
    "":
      map:
        default: {string: {margin: 8, <<: [*default, *bgb]}}
        conditions:
          state == focused: {string: {margin: 8, <<: [*default, *focused]}}

# album artist?
mpd: &mpd
  host: /run/mpd/socket
  content:
    string: {text: "artist - title (album)", margin: 8, <<: *bgb}

pipewire: &pipewire
  anchors:
    vol: &vol
      <<: *bgb
      on-click:
        left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
        wheel-up: "pactl set-sink-volume @DEFAULT_SINK@ +5%"
        wheel-down: "pactl set-sink-volume @DEFAULT_SINK@ -5%"
  content:
    map:
      conditions:
        type == "sink" && muted: {string: {text: "", margin: 8, <<: *bgb, font: *icons, on-click: "pactl set-sink-mute @DEFAULT_SINK@ toggle"}}
        type == "sink" && ~muted:
          list:
            spacing: 0
            items:
              - ramp:
                  tag: cubic_volume
                  items:
                    - string: {text: "", font: *icons, left-margin: 8, <<: *vol}
                    - string: {text: "", font: *icons, left-margin: 8, <<: *vol}
                    - string: {text: "", font: *icons, left-margin: 8, <<: *vol}
              - string: {text: "{cubic_volume}", left-margin: 4, right-margin: 8, <<: *vol}

network: &network
  content:
    map:
      conditions:
        state == up && carrier && name >= wl:
          string: {text: " {ssid} {dl-speed:mb:.1}{ul-speed:mb:.1}", margin: 8, <<: *bgb}
        state == up && carrier && name <= en:
          string: {text: " {name} {dl-speed:mb:.1}{ul-speed:mb:.1}", margin: 8, <<: *bgb}

battery: &battery
  name: BAT1
  poll-interval: 30000
  content:
    map:
      conditions:
        capacity != 0: {string: {text: "󰁹 {capacity}%", margin: 8, <<: *bgb}}

clock: &clock
  foreground: *bg
  time-format: "%H:%M"
  date-format: "%a, %b %d"
  content:
    string: {text: "{time} | {date}", margin: 8, <<: *c2b}

bar:
  monitor: DP-1 # How's this gonna work with a laptop?
  height: 32
  location: top

  font: *ios

  foreground: *c2
  background: *trans

  left:
    - i3: *i3

  right:
    - network: *network
    - pipewire: *pipewire
    - battery: *battery
    - clock: *clock
