
i3: &i3
  i3:
    anchors: # Not used (directly) by f00bar; used here to avoid duplication
      - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
      - string: &default {<<: *i3_common, text:  "{name}"}
      - focused: &focused
          foreground: *background
          deco: {stack: [background: {color: *color4}]}
    content:
      "":
        map:
          conditions:
            state == focused:   {string: {<<: [*default, *focused]}}
            state == invisible: {string: {<<: *default}}

pipewire: &pipewire
  pipewire:
    anchors:
      volume: &volume
        conditions:
          muted: 
            string:
              text: " {cubic_volume}%"
              on-click:
                left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
                wheel-up: "pactl set-sink-volume @DEFAULT_SINK@ +1%"
                wheel-down: "pactl set-sink-volume @DEFAULT_SINK@ -1%"

          ~muted:
            string:
              text: " {cubic_volume}%"
              on-click:
                left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
                wheel-up: "pactl set-sink-volume @DEFAULT_SINK@ +1%"
                wheel-down: "pactl set-sink-volume @DEFAULT_SINK@ -1%"
    content:
      list:
        items:
          - map:
              conditions:
                type == "sink":
                  map:
                    <<: *volume

battery: &battery
  battery:
    name: BAT1
    poll-interval: 30000
    content:
      string:
        text: " {capacity}%"

clock: &clock
  clock:
    time-format: "%H:%M"
    date-format: "%m/%d"
    content:
      - string: {text: " {date}"}
      - string: {text: " {time}"}

bar:
  height: 40
  location: top
  spacing: 5
  margin: 10

  font: IosevkaNerdFont:pixelsize=32:fontfeatures=ss20

  foreground: *foreground
  background: *background

  left:
   - *pipewire

  center:
   - *i3

  right:
   - *battery
   - *clock
