# Typical laptop setup, with wifi, brightness, battery etc, for
# i3/Sway.

# For X11/i3, you'll want to replace calls to swaymsg with i3-msg, and
# the sway-xkb module with the xkb module.

# fonts we'll be re-using here and there
icon-margin: &icon-margin {left-margin: 6, right-margin: 6} 
std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  height: 40
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: IosevkaNerdFont:pixelsize=32:fontfeatures=ss20

  foreground: ffffffff
  background: 111111cc

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  center:
    - i3:
        anchors: # Not used (directly) by f00bar; used here to avoid duplication
          - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
          - string: &default {<<: *i3_common, text:  "{name}"}
          - focused: &focused
              deco: {stack: [background: {color: ffa0a04c}, <<: *std_underline]}
          - invisible: &invisible {foreground: ffffff55}
          - urgent: &urgent
              foreground: 000000ff
              deco: {stack: [background: {color: bc2b3fff}, <<: *std_underline]}
          - map: &i3_mode
              default:
                - string:
                    margin: 5
                    text: "{mode}"
                    deco: {background: {color: cc421dff}}
                - empty: {right-margin: 7}
              conditions:
                mode == default: {empty: {}}
        content:
          "":
            map:
              conditions:
                state == focused:   {string: {<<: [*default, *focused]}}
                state == unfocused: {string: {<<: *default}}
                state == invisible: {string: {<<: [*default, *invisible]}}
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", foreground: ffa0a0ff}
                - string: {text: ": {title}"}
# center:
#   - mpd:
#       host: /run/mpd/socket
#       anchors:
#         list: &artist_album_title
#           spacing: 0
#           items:
#             - map:
#                 conditions:
#                   state == playing: {string: {text: "{artist}"}}
#                   state == paused: {string: {text: "{artist}", foreground: ffffff66}}
#             - string: {text: " | ", foreground: ffffff66}
#             - map:
#                 conditions:
#                   state == playing: {string: {text: "{album}"}}
#                   state == paused: {string: {text: "{album}", foreground: ffffff66}}
#             - string: {text: " | ", foreground: ffffff66}
#             - map:
#                 conditions:
#                   state == playing: {string: {text: "{title}", foreground: ffa0a0ff}}
#                   state == paused: {string: {text: "{title}", foreground: ffffff66}}
#
#       content:
#         map:
#           margin: 10
#           conditions:
#             state == offline: {string: {text: offline, foreground: ff0000ff}}
#             state == stopped: {string: {text: stopped}}
#             state == paused: {list: *artist_album_title}
#             state == playing: {list: *artist_album_title}

  right:
   - battery:
        name: BAT1
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff}
                      - string: {text: , foreground: ffa600ff}
                      - string: {text: ,}
                      - string: {text: ,}
                      - string: {text: ,}
                      - string: {text: ,}
                      - string: {text: ,}
                      - string: {text: ,}
                      - string: {text: ,}
                      - string: {text: , foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
              state == full:
                - string: {text: , foreground: 00ff00ff}
                - string: {text: " {capacity}% full"}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff}
                      - string: {text:  , foreground: ffa600ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                - string: {text: " {capacity}%"}
   - clock:
        time-format: "%H:%M"
        date-format: "%m/%d"
        content:
          - string: {text: }
          - string: {text: " {date} {time}", right-margin: 5}
   - label:
        content:
          string:
            on-click: systemctl poweroff
            text: 
            right-margin: 30
