
i3: &i3
  i3:
    anchors: # Not used (directly) by f00bar; used here to avoid duplication
      - string: &i3_common {margin: 5, on-click: "swaymsg --quiet workspace {name}"}
      - string: &default {<<: *i3_common, text:  "{name}"}
      - focused: &focused
          foreground: *foreground
          deco:
            underline: 
              size: 5
              color: *color4
    sort: ascending
    content:
      "":
        map:
          conditions:
            state == focused:   {string: {<<: [*default, *focused]}}
            state != focused: {string: {<<: *default}}

pipewire: &pipewire
  pipewire:
    anchors:
      volume: &volume
        conditions:
          muted: 
            string:
              text: "[vol: mute]"
              on-click: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
          ~muted:
            string:
              text: "[vol: {cubic_volume}%]"
              on-click:
                left: "pactl set-sink-mute @DEFAULT_SINK@ toggle"
                wheel-up: "pactl set-sink-volume @DEFAULT_SINK@ +1%"
                wheel-down: "pactl set-sink-volume @DEFAULT_SINK@ -1%"
    content:
      list:
        items:
          - map:
              conditions:
                type == "sink":
                  map:
                    <<: *volume
                    foreground: *color2

battery: &battery
  battery:
    name: BAT1
    poll-interval: 30000
    content:
      string:
        text: "[bat: {capacity}%]"
        foreground: *color5

clock: &clock
  clock:
    time-format: "%H:%M"
    date-format: "%a, %b %d"
    content:
      - string: {text: "{time} {date}"}

bar:
  height: 40
  location: top
  spacing: 5
  margin: 10

  font: IosevkaNerdFont:pixelsize=32:fontfeatures=ss20

  foreground: *foreground
  background: *background

  left:
   - *i3

  center:
   - *clock

  right:
   - *pipewire
   - *battery
